#!/bin/bash
cwd=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

###############################################################################
# Custom Steps
###############################################################################

# SETUP_ROOT=$HOME/.setup

# NERDFONTS_VERSION=$(get_github_version_latest ryanoasis/nerd-fonts)

# NERDFONTS=(
#   SpaceMono
#   Hack
#   AnonymousPro
#   Inconsolata
# )

readonly DIRECTORIES=(
  "$HOME/code"
  "$HOME/Downloads"
)

readonly DOTFILES_ROOT=$cwd/dotfiles

step "Making directories…"
for dir in "${DIRECTORIES[@]}"; do
  mkd "$dir"
done

step "Symlinking dotfiles…"
symlink_dotfiles

# step "Creating local config files"
# create_gitconfig_local

step "Installing latest version of bat"
install_bat

step "Installing latest version of neovim"
if [[ ! -e /etc/apt/sources.list.d/neovim-ppa-ubuntu-stable-focal.list ]]; then
  # need to add ppa
  sudo sh -c "sudo add-apt-repository ppa:neovim-ppa/stable -y &> /dev/null"
  # automatically performs apt update after adding
fi
# install if not yet installed; update if already installed
sudo apt-get install -yqq neovim
print_success "neovim installed"
# TODO: redo dotfiles linking config so that this step isn't necessary
NVIM_CONFIG="$HOME/.config/nvim/init.vim"
if [[ ! -e "$NVIM_CONFIG" ]]; then
  mkd "$HOME/.config/nvim"
  touch "$NVIM_CONFIG"
  printf "%s\n" \
"set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc" \
  >> "$NVIM_CONFIG"
fi

step "Installing gh cli"
if ! grep -q "^deb https://cli.github.com" /etc/apt/sources.list; then
  # need to add ppa
  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
  sudo sh -c "sudo apt-add-repository https://cli.github.com/packages"
  # automatically performs apt update after adding
fi
sudo apt-get install -yqq gh

# step "Installing fonts…"
# for font in ${NERDFONTS[@]}; do
#     if [ ! -d ~/Library/Fonts/$font ]; then
#         printf "${indent}  [↓] $font "
#         wget -P ~/Library/Fonts https://github.com/ryanoasis/nerd-fonts/releases/download/$NERDFONTS_VERSION/$font.zip --quiet;unzip -q ~/Library/Fonts/$font -d ~/Library/Fonts/$font
#         print_in_green "${bold}✓ done!${normal}\n"
#     else
#         print_muted "${indent}✓ $font already installed. Skipped."
#     fi
# done