#!/bin/bash

# SETUP_ROOT=$HOME/.setup

# NERDFONTS_VERSION=$(get_github_version_latest ryanoasis/nerd-fonts)

DIRECTORIES=(
  "$HOME/code"
  "$HOME/Downloads"
)



# NERDFONTS=(
#   SpaceMono
#   Hack
#   AnonymousPro
#   Inconsolata
# )

step "Making directories…"
for dir in "${DIRECTORIES[@]}"; do
  mkd "$dir"
done

step "Symlinking dotfiles…"
symlink_dotfiles

step "Creating local config files"
create_gitconfig_local

step "Installing latest version of bat"
BAT_VERSION=$(get_github_version_latest sharkdp/bat)
# remove 'v' from filename (ex v0.17.1 => 0.17.1)
BAT_FILENAME=bat_${BAT_VERSION#v}_amd64.deb
if [[ -x $(command -v bat) ]] || [[ -x $(command -v batcat) ]] ; then
  # bat is installed; check for updates
  INSTALLED_BAT_VERSION=$(get_installed_package_version bat)
  if dpkg --compare-versions "$INSTALLED_BAT_VERSION" "lt" "${BAT_VERSION#v}"; then
    # update bat
    install_update_dpkg "https://github.com/sharkdp/bat/releases/download/$BAT_VERSION/$BAT_FILENAME"
    print_in_green "    ✓ bat $BAT_VERSION installed\n"
  else
    print_success_muted "bat already installed and up to date. Skipping"
  fi
else
  # bat not yet installed
  install_update_dpkg "https://github.com/sharkdp/bat/releases/download/$BAT_VERSION/$BAT_FILENAME"
  print_in_green "    ✓ bat $BAT_VERSION installed\n"
fi

step "Installing latest version of neovim"
if [[ ! -e /etc/apt/sources.list.d/neovim-ppa-ubuntu-stable-focal.list ]]; then
  # need to add ppa
  sudo sh -c "sudo add-apt-repository ppa:neovim-ppa/stable -y &> /dev/null"
  # automatically performs apt update after adding
fi
# install if not yet installed; update if already installed
sudo apt-get install -yqq neovim
print_in_green "    ✓ neovim installed\n"
# TODO: redo dotfiles linking config so that this step isn't necessary
NVIM_CONFIG="$HOME/.config/nvim/init.vim"
if [[ ! -e "$NVIM_CONFIG" ]]; then
  mkd "$HOME/.config/nvim"
  touch "$NVIM_CONFIG"
  printf "%s\n" \
"set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc" \
  >> "$NVIM_CONFIG"
fi



# step "Installing fonts…"
# for font in ${NERDFONTS[@]}; do
#     if [ ! -d ~/Library/Fonts/$font ]; then
#         printf "${indent}  [↓] $font "
#         wget -P ~/Library/Fonts https://github.com/ryanoasis/nerd-fonts/releases/download/$NERDFONTS_VERSION/$font.zip --quiet;unzip -q ~/Library/Fonts/$font -d ~/Library/Fonts/$font
#         print_in_green "${bold}✓ done!${normal}\n"
#     else
#         print_muted "${indent}✓ $font already installed. Skipped."
#     fi
# done